# Generated by Django 3.1.4 on 2022-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='state',
            field=models.CharField(blank=True, max_length=150, verbose_name='State'),
        ),
    ]
