# Generated by Django 3.1.14 on 2022-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220616_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id', '-created')},
        ),
        migrations.AlterField(
            model_name='order',
            name='address1',
            field=models.CharField(max_length=250, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False, verbose_name='Billing status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(max_length=200, verbose_name='Order key'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='Post code'),
        ),
    ]
