# Generated by Django 4.1 on 2022-08-11 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_on_time_use_voucher_one_time_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='one_time_use',
            field=models.BooleanField(help_text='code can be used once for each user.', verbose_name='one time use'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 11, 50, 57, 759857, tzinfo=datetime.timezone.utc), verbose_name='valid voucher from'),
        ),
    ]
