# Generated by Django 4.1 on 2022-08-11 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_voucher_one_time_use_alter_voucher_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(default=1, max_length=10, verbose_name='vocuher code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 12, 9, 28, 919208, tzinfo=datetime.timezone.utc), verbose_name='valid voucher from'),
        ),
    ]
