# Generated by Django 4.1 on 2022-08-12 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_voucher_max_use_alter_voucher_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 7, 50, 26, 754437, tzinfo=datetime.timezone.utc), verbose_name='valid voucher from'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='vocuher code'),
        ),
    ]
