# Generated by Django 4.1 on 2022-08-13 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_voucher_valid_from_alter_voucher_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='valid voucher from'),
        ),
    ]
