# Generated by Django 3.2.4 on 2022-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20220219_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_picture',
            field=models.ImageField(upload_to='Products/<bound method Field.__str__ of <django.db.models.fields.CharField>>', verbose_name='Main picture'),
        ),
    ]
