# Generated by Django 3.2.4 on 2022-02-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_main_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
