# Generated by Django 3.2.4 on 2022-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name='Picture 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name='Picture 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='Products/', verbose_name='Picture 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
